# Generated by Django 3.2 on 2022-05-30 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_state_orders_status'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatechatroom',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='user.joinbrand'),
        ),
        migrations.AlterField(
            model_name='privatechatroom',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='user.joininfluencer'),
        ),
        migrations.AlterField(
            model_name='roomchatmessage',
            name='user',
            field=models.IntegerField(),
        ),
    ]
