# Generated by Django 3.2.6 on 2022-07-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_privatechatroom_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechatroom',
            name='order',
        ),
    ]
