# Generated by Django 3.2.6 on 2022-07-22 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_orders_price'),
        ('chat', '0005_remove_privatechatroom_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechatroom',
            name='order',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='user.orders'),
        ),
    ]
