# Generated by Django 3.2.6 on 2022-07-26 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_remove_privatechatroom_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privatechatroom',
            name='user1',
        ),
        migrations.RemoveField(
            model_name='privatechatroom',
            name='user2',
        ),
        migrations.AddField(
            model_name='privatechatroom',
            name='brand',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='brand', to=settings.AUTH_USER_MODEL),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='privatechatroom',
            name='influencer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencer', to=settings.AUTH_USER_MODEL),
        ),
    ]
