# Generated by Django 3.2.6 on 2022-07-26 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_orders_price'),
        ('chat', '0009_auto_20220727_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='privatechatroom',
            name='brand',
            field=models.ForeignKey(null=b'I01\n', on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='user.joinbrand'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='privatechatroom',
            name='influencer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='influencer', to='user.joininfluencer'),
        ),
    ]
