# Generated by Django 3.2 on 2022-05-16 19:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_submit_requirements'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joinbrand',
            name='brand_email',
        ),
        migrations.AddField(
            model_name='joinbrand',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
