# Generated by Django 3.2 on 2022-05-16 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20220517_0020'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.joinbrand')),
                ('influencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.joininfluencer')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.influencerpackage')),
            ],
        ),
        migrations.AddField(
            model_name='submit_requirements',
            name='orders',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.orders'),
        ),
    ]
