# Generated by Django 3.2 on 2022-05-16 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20220517_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit_requirements',
            name='user',
        ),
    ]
