# Generated by Django 3.2 on 2022-05-16 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_submit_requirements_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submit_requirements',
            name='product_cost',
        ),
    ]
