# Generated by Django 3.2 on 2022-05-16 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_orders_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='status',
            new_name='state',
        ),
    ]
