# Generated by Django 3.2 on 2022-05-16 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_rename_status_orders_state'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='state',
            new_name='status',
        ),
    ]
