# Generated by Django 3.2.6 on 2022-06-13 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_joininfluencer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreviousExprience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exprience_title', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('influencer_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.joininfluencer')),
            ],
        ),
        migrations.CreateModel(
            name='PreviousExprienceImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('influencer_username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.previousexprience')),
            ],
        ),
    ]
