# Generated by Django 3.2.6 on 2022-06-15 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20220614_0258'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='crated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
