# Generated by Django 3.2.6 on 2022-06-15 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_orders_crated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='crated_at',
        ),
    ]
