# Generated by Django 3.2.6 on 2022-06-24 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_orders_crated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinbrand',
            name='crated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='joininfluencer',
            name='crated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
