# Generated by Django 3.2.6 on 2022-07-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20220625_0303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='crated_at',
            field=models.DateField(null=True),
        ),
    ]
