# Generated by Django 3.2.6 on 2022-07-19 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_orders_crated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='crated_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
