# Generated by Django 3.2.6 on 2022-07-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_orders_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='package_category',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='package_description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='package_platform',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='token',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
