# Generated by Django 3.2.6 on 2022-07-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_auto_20220728_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
