# Generated by Django 3.2 on 2022-04-13 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_editportfolioimages_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='influencerpackage',
            name='choose_platform',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='influencerpackage',
            name='content_category',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='influencerpackage',
            name='package_include',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='influencerpackage',
            name='package_offering',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='influencerpackage',
            name='package_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
