# Generated by Django 3.2 on 2022-04-15 19:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0022_auto_20220414_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('brand_name', models.CharField(max_length=50)),
                ('brand_email', models.EmailField(max_length=300)),
                ('brand_website', models.URLField(blank=True, max_length=300, null=True)),
                ('brand_instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_tiktok', models.CharField(blank=True, max_length=50, null=True)),
                ('brand_youtube', models.URLField(blank=True, max_length=300, null=True)),
                ('brand_location', models.CharField(blank=True, max_length=100, null=True)),
                ('brand_description', models.CharField(blank=True, max_length=400, null=True)),
                ('lifestyle', models.BooleanField(default=False)),
                ('fashion', models.BooleanField(default=False)),
                ('beauty', models.BooleanField(default=False)),
                ('health_fitness', models.BooleanField(default=False)),
                ('travel', models.BooleanField(default=False)),
                ('food_drink', models.BooleanField(default=False)),
                ('model', models.BooleanField(default=False)),
                ('comedy_entertainment', models.BooleanField(default=False)),
                ('art_photography', models.BooleanField(default=False)),
                ('music_dance', models.BooleanField(default=False)),
                ('entrepreneur_business', models.BooleanField(default=False)),
                ('family_children', models.BooleanField(default=False)),
                ('animals_pets', models.BooleanField(default=False)),
                ('athlete_sports', models.BooleanField(default=False)),
                ('celebrity_public_pigure', models.BooleanField(default=False)),
                ('adventure_outdoors', models.BooleanField(default=False)),
                ('actor', models.BooleanField(default=False)),
                ('education', models.BooleanField(default=False)),
                ('gaming', models.BooleanField(default=False)),
                ('lgbtq', models.BooleanField(default=False)),
                ('technology', models.BooleanField(default=False)),
                ('healthcare', models.BooleanField(default=False)),
                ('vegan', models.BooleanField(default=False)),
                ('cannabis', models.BooleanField(default=False)),
                ('skilled_trades', models.BooleanField(default=False)),
                ('automotive', models.BooleanField(default=False)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='BrandorInfluencer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.BooleanField(default=False)),
                ('influencer', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
