# Generated by Django 3.2 on 2022-04-16 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_joinbrand_brand_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinbrand',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
