# Generated by Django 3.2 on 2022-04-16 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_joinbrand_is_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brandorinfluencer',
            name='influencer',
        ),
    ]
